version: '3.1'
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_INITDB_DATABASE=cms
            - MONGO_INITDB_ROOT_USERNAME=xapp
            - MONGO_INITDB_ROOT_PASSWORD=password
        ports:
            - "27017:27017"
        volumes:
            - './mongodb/db:/data/db'
